//
// Car.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct Car: Codable {

    public var id: Int64
    /** Название */
    public var name: String
    /** Гос номер */
    public var govNumber: String
    /** ID водителя к которому привязана машина */
    public var driverId: Int64

}
