//
// TransportApplicationResponseDriver.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TransportApplicationResponseDriver: Codable {

    public var _id: Int64?
    public var name: String?
    public var phone: String?
    public var car: Car?

    public init(_id: Int64? = nil, name: String? = nil, phone: String? = nil, car: Car? = nil) {
        self._id = _id
        self.name = name
        self.phone = phone
        self.car = car
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case phone
        case car
    }

}
