//
// LoginResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct LoginResponse: Codable {

    public let accessToken: String
    public let refreshToken: String

}
