//
// LoginResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

public struct LoginResponse: Decodable {

    public let accessToken: String
    public let refreshToken: String
    public let user: User

}
