//
// TransportApplication.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct TransportApplication: Decodable {

    public var passenger: Passenger
    public var driver: Driver
    public var address: String
    public var date: String
    public var timeRange: String
    public var comment: String?

    // MARK: - Public Methods
    public static func getFake() -> TransportApplication {
        return TransportApplication(passenger: Passenger.getFake(), driver: Driver.getFake(), address: "ул. Оборонная, 1", date: "18.07.2021", timeRange: "10:00-11:00", comment: "Таким образом сложившаяся структура организации представляет собой интересный эксперимент проверки новых предложений. Повседневная практика показывает, что постоянное информационно-пропагандистское обеспечение нашей деятельности способствует подготовки и реализации дальнейших направлений развития. Разнообразный и богатый опыт консультация с широким активом представляет собой интересный эксперимент проверки соответствующий условий активизации.")
    }

}
