//
// TransportApplicationRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct TransportApplicationRequest: Codable {

    public var passengerId: String
    public var driverId: String
    public var address: String
    public var date: String
    public var timeRange: String
    public var comment: String?

}
